port_configs:
  - type: USP
  - type: DSP
  - type: DSP
virtual_switch_configs:
  - upstream_port_index: 0
    vppb_counts: 6
    initial_bounds: [[1,0],[1,1],[1,2],[1,3],[2,0],[2,1]]
devices:
  multi_logical_devices:
    - port_index: 1
      serial_number: 3FB95963144632BF
      logical_devices:
      - memory_size: 256M
        ld_id: 0
      - memory_size: 256M
        ld_id: 1
      - memory_size: 256M
        ld_id: 2
      - memory_size: 256M
        ld_id: 3
    - port_index: 2
      serial_number: 8A440DABC4DBEAFB
      logical_devices:
      - memory_size: 512M
        ld_id: 0
      - memory_size: 512M
        ld_id: 1
