port_configs:
  - type: USP
  - type: DSP
  - type: DSP
  - type: DSP
  - type: DSP
  - type: DSP
  - type: DSP
virtual_switch_configs:
  - upstream_port_index: 0
    vppb_counts: 10
    initial_bounds: [1,2,3,4,5,5,5,5,6,6]
devices:
  single_logical_devices:
    - port_index: 1
      memory_size: 256M
      serial_number: 4E9FF1671694A385
    - port_index: 2
      memory_size: 256M
      serial_number: 2200B90031B3ABD8
    - port_index: 3
      memory_size: 256M
      serial_number: 3B0357B80F50A534
    - port_index: 4
      memory_size: 256M
      serial_number: CB6575D3D9A4FC7A
  multi_logical_devices:
    - port_index: 5
      serial_number: 3FB95963144632BF
      logical_devices:
      - memory_size: 256M
      - memory_size: 256M
      - memory_size: 256M
      - memory_size: 256M
    - port_index: 6
      serial_number: 8A440DABC4DBEAFB
      logical_devices:
      - memory_size: 512M
      - memory_size: 512M
