port_configs:
  - type: USP
  - type: DSP
  - type: USP
virtual_switch_configs:
  - upstream_port_index: 0
    vppb_counts: 4
    initial_bounds: [[1,0],[1,1],[1,2],[1,3]]
  - upstream_port_index: 2
    vppb_counts: 4
    initial_bounds: [[1,4],[1,5],[1,6],[1,7]]
devices:
  multi_logical_devices:
    - port_index: 1
      serial_number: 3FB95963144632BF
      logical_devices:
      - memory_size: 256M
        ld_id: 0
      - memory_size: 256M
        ld_id: 1
      - memory_size: 256M
        ld_id: 2
      - memory_size: 256M
        ld_id: 3
      - memory_size: 256M
        ld_id: 4
      - memory_size: 256M
        ld_id: 5
      - memory_size: 256M
        ld_id: 6
      - memory_size: 256M
        ld_id: 7
